export const SAVE_PROBLEMS = 'SAVE_PROBLEMS';
export const UPDATE_PROBLEMS = 'UPDATE_PROBLEMS';
export const DELETE_PROBLEMS = 'DELETE_PROBLEMS';
export const SAVE_SIMILARS = 'SAVE_SIMILARS';
export const UPDATE_SIMILARS = 'UPDATE_SIMILARS';
export const SHOW_SIMILARS = 'SHOW_SIMILARS';
export const HIDE_SIMILARS = 'HIDE_SIMILARS';